# Generated by Django 4.2.9 on 2024-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('companyName', models.CharField(max_length=200)),
                ('companyRegion', models.CharField(max_length=200)),
                ('salaryRange', models.CharField(max_length=200)),
                ('jobDescription', models.CharField(max_length=900)),
                ('applicationDate', models.CharField(max_length=200)),
                ('jobRequirements', models.CharField(max_length=900)),
                ('applicationLink', models.CharField(max_length=400)),
            ],
        ),
    ]
